# Generated by Django 2.0.7 on 2019-01-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190131_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.CharField(default='1', max_length=128),
        ),
    ]
